<!DOCTYPE html>
	<%! String mess="";%>
<%
	response.setHeader("Cache-Control","no-store, no-cache, must-revalidate");
	response.setHeader("expires","now");
	response.setHeader("pragma","no-cache");
%>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<title>Data Mining</title>
	<link rel="stylesheet" href="style.css" type="text/css" charset="utf-8" />
<script type="text/javascript">
</script>
</head>
<body>
	<form name="contact" method="post">
  <div id="wrapper">
    <div id="header"> </div>
    <div id="left">
      <div id="logo">
       
      </div>
      <div id="nav">
        <ul>
          <li><a href="index.jsp">Home</a></li>
          <li><a href="userregister.jsp">Register</a></li>
          <li><a href="userlogin.jsp">Login</a></li>         
          <li class="important"><a href="contact.jsp">Contact us</a></li>
        </ul>
      </div>
      <div id="news">
       <p></p>
      	<p>&nbsp;</p>
      	<p>&nbsp;</p>
      	<p>&nbsp;</p>
      	<p>&nbsp;</p>
      	<p>&nbsp;</p>
      	<p>&nbsp;</p>
      	<p>&nbsp;</p>
      	<p>&nbsp;</p>
      	<p>&nbsp;</p>
      </div>
      <div id="support">
       
      </div>
    </div>
    <div id="right">
      <h2>Contact Page<br />
   	  </h2>
      <p>Random forests are an idea of the general technique of random decision forests that are an
        ensemble learning technique for classification, regression and other tasks, that control by
        constructing a multitude of decision trees at training time and outputting the class that is the mode
        of the classes (classification) or mean prediction (regression) of the individual trees. Random
        decision forests accurate for decision trees' habit of overfitting to their training set.
        A Random Forest is a classifier consisting of collection of tree-structured classifiers where
        independent random vectors are distributed identically and each tree cast a unit vote for the most
        popular class at input x. A random vector is generated which is independent of the past random
      vectors with same distribution and a tree is generated by using the training test [Brieman (2001)]</p>
    </div>
    <div class="clear"> </div>
    <div id="spacer"> </div>
    <div id="footer">
      <div id="copyright">
       
      </div>
	  <div id="footerline"></div>
    </div>

  </div>
  </form>
</body>
</html>
